export const sampleHousehold = {
  primary: {
    firstName: "Steve",
    lastName: "Tipton",
    email: "tipton1456@gmail.com",
    phone: "(662) 555-1234",
    mobile: "(662) 555-1234",
    birthday: "Not listed",
    address: "123 Sample Street, Tupelo, MS 38801",
  },
  family: [
    {
      firstName: "Kyla",
      lastName: "Tipton",
      relationship: "Spouse",
      email: "kyla@example.com",
      phone: "(662) 555-5678",
      mobile: "(662) 555-5678",
      birthday: "Not listed",
    },
    {
      firstName: "Kailynn",
      lastName: "Tipton",
      relationship: "Child",
      email: "",
      phone: "",
      mobile: "",
      birthday: "Not listed",
    },
    {
      firstName: "Kenna",
      lastName: "Tipton",
      relationship: "Child",
      email: "",
      phone: "",
      mobile: "",
      birthday: "Not listed",
    },
  ],
};
