export const sampleHousehold = {
  primary: {
    id: "sample-primary",
    firstName: "Daniel",
    lastName: "Demo",
    email: "demo@apostoliclife.local",
    phone: "(662) 555-1200",
    mobile: "(662) 555-1201",
    birthday: "January 14, 1984",
    birthdayValue: "1984-01-14",
    picture: "https://i.pravatar.cc/160?img=12",
    address: "1100 Main Street, Tupelo, MS 38801",
    addressFields: {
      line1: "1100 Main Street",
      line2: "",
      city: "Tupelo",
      state: "MS",
      postcode: "38801",
      country: "United States",
    },
  },
  family: [
    {
      id: "sample-kyla",
      firstName: "Maria",
      lastName: "Demo",
      relationship: "Spouse",
      email: "maria.demo@example.com",
      phone: "(662) 555-1210",
      mobile: "(662) 555-1211",
      birthday: "March 8, 1986",
      birthdayValue: "1986-03-08",
      picture: "https://i.pravatar.cc/160?img=47",
    },
    {
      id: "sample-kailynn",
      firstName: "Avery",
      lastName: "Demo",
      relationship: "Child",
      email: "demo@apostoliclife.local",
      phone: "(662) 555-1220",
      mobile: "",
      birthday: "July 22, 2012",
      birthdayValue: "2012-07-22",
      picture: "https://i.pravatar.cc/160?img=32",
    },
    {
      id: "sample-kenna",
      firstName: "Eli",
      lastName: "Demo",
      relationship: "Child",
      email: "eli.demo@example.com",
      phone: "(662) 555-1225",
      mobile: "",
      birthday: "September 4, 2015",
      birthdayValue: "2015-09-04",
      picture: "https://i.pravatar.cc/160?img=15",
    },
  ],
};
